# Generated by Django 5.2.15 on 2026-06-22 12:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pack', models.CharField(choices=[('mini', 'Pack Mini'), ('medio', 'Pack Medio'), ('grande', 'Pack Grande'), ('legendario', 'Pack Legendario')], max_length=20)),
                ('amount', models.PositiveIntegerField(help_text='Monto en centimos. Ejemplo: S/ 1.00 = 100')),
                ('discs_purchased', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=120)),
                ('provider', models.CharField(default='culqi', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
