# Generated by Django 6.1 on 2026-09-10 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilPromocionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('yo', 'Yo'), ('artista', 'Artista'), ('programador', 'Programador'), ('amigo', 'Amigo'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='perfiles_promocionados/')),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('plataforma', models.CharField(choices=[('twitter', 'X / Twitter'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('discord', 'Discord'), ('carrd', 'Carrd'), ('patreon', 'Patreon'), ('itch', 'itch.io'), ('github', 'GitHub'), ('otro', 'Otro')], max_length=20)),
                ('url', models.URLField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
