# Generated by Django 6.1 on 2026-09-10 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icono', models.ImageField(blank=True, null=True, upload_to='platform_icons/')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='sociallink',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='plataforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paginas.platform'),
        ),
    ]
