# Generated by Django 5.2.12 on 2026-04-07 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_commentvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmojiPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='customemoji',
            name='image',
            field=models.FileField(upload_to='emojis/'),
        ),
        migrations.AddField(
            model_name='customemoji',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emojis', to='blog.emojipack'),
        ),
    ]
