# Generated by Django 5.2.12 on 2026-04-05 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField(blank=True)),
                ('template_type', models.CharField(choices=[('full', 'Con layout completo'), ('minimal', 'Sin header ni footer'), ('blank', 'Página en blanco'), ('custom', 'Template personalizado')], default='full', max_length=20)),
                ('custom_template', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('access_hour_start', models.IntegerField(blank=True, null=True)),
                ('access_hour_end', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntrySecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(max_length=200)),
                ('achievement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.achievement')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='entries.entry')),
            ],
        ),
    ]
